name: Linting and Testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Security check - Bandit
        uses: joshvote/bandit-report-artifacts@v0.0.3
        with:
          project_path: .
          ignore_failure: false
          config_file: pyproject.toml

      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Security report
          path: output/security_report.txt

  flake8_py311:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.11"

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Lint with flake8
        if: always()
        run: |
          pip install flake8
          flake8 . --count --statistics

  black_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  mypy_py311:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.ENVOY_SCHEMA_PRIVATE_KEY }}'
          pip install .[dev]

      - name: Add mypy annotator
        uses: pr-annotators/mypy-pr-annotator@v1.0.0

      - name: Run mypy
        run: |
          mypy src/

  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        run: |
          echo $'{ "experimental": true, "features": { "buildkit" : true } }' | sudo tee /etc/docker/daemon.json
          echo '${{ secrets.BSGIP_PAT }}' > ./github.pat
          echo '${{ secrets.GITLAB_PAT }}' > ./gitlab.pat
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
          docker build -t envoy:test -f Dockerfile.server --secret id=github_pat,src=github.pat . --no-cache

  pytest_py310:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.ENVOY_SCHEMA_PRIVATE_KEY }}'
          sudo apt install -y postgresql
          pip install .[test]

      - name: Run Pytest
        run: |
          pytest --junit-xml=.test_report.xml
        env:
          DATABASE_URL: "postgresql+asyncpg://faketestcred:faketestcred@faketestcred/faketestcred"
          ADMIN_USERNAME: "testadmin"
          ADMIN_PASSWORD: "testpassword"
      - name: Upload Results
        uses: test-summary/action@v1
        with:
          paths: .test_report.xml
        if: always()

  pytest_py311:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.ENVOY_SCHEMA_PRIVATE_KEY }}'
          sudo apt install -y postgresql
          pip install .[test]

      - name: Run Pytest
        run: |
          pytest --junit-xml=.test_report.xml
        env:
          DATABASE_URL: "postgresql+asyncpg://faketestcred:faketestcred@faketestcred/faketestcred"
          ADMIN_USERNAME: "testadmin"
          ADMIN_PASSWORD: "testpassword"
      - name: Upload Results
        uses: test-summary/action@v1
        with:
          paths: .test_report.xml
        if: always()
